spring.application.name=bookmaker

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


# # Enable the H2 web console (optional, default is false)
# spring.h2.console.enabled=true
# # Set the path for the H2 web console (optional, default is /h2-console)
# spring.h2.console.path=/h2-console

# # JDBC driver class name
# spring.datasource.driver-class-name=org.h2.Driver

# # JDBC URL for the database connection
# # Examples of URLs are provided below
# spring.datasource.url=jdbc:h2:mem:testdb

# # Database username
# spring.datasource.username=sa

# # Database password
# spring.datasource.password=


spring.flyway.locations=classpath:/db/migration/{vendor}


